[package]
name = "moshpit"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mp"
path = "src/main.rs"

[features]
unstable = []

[dependencies]
anyhow = { workspace = true }
aws-lc-rs = { workspace = true }
bon = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
getset = { workspace = true }
hex = "0.4.3"
libmoshpit = { version = "0.1.0", path = "../libmoshpit" }
serde = { workspace = true }
tokio = { workspace = true, features = ["sync","time"] }
tracing = { workspace = true }
tracing-subscriber-init = { workspace = true }
uuid = { workspace = true }
vergen-pretty = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage,coverage_nightly)',
] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
